// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfnakSXR9LsTuNwOZU22W29DSpeCpFVrI',
    appId: '1:969788980087:web:507244599053627a7dff72',
    messagingSenderId: '969788980087',
    projectId: 'medicine-b7e88',
    authDomain: 'medicine-b7e88.firebaseapp.com',
    storageBucket: 'medicine-b7e88.appspot.com',
    measurementId: 'G-3Q5NMVGTQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD336VKax7pTd4cjt7Oa6vc6ejKTFsKBsI',
    appId: '1:969788980087:android:9775efd816ea0c6a7dff72',
    messagingSenderId: '969788980087',
    projectId: 'medicine-b7e88',
    storageBucket: 'medicine-b7e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcA0tT3RUOjSln54I6_FASC5ExzN3215Q',
    appId: '1:969788980087:ios:561b0b903f1a707c7dff72',
    messagingSenderId: '969788980087',
    projectId: 'medicine-b7e88',
    storageBucket: 'medicine-b7e88.appspot.com',
    iosBundleId: 'com.example.medicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcA0tT3RUOjSln54I6_FASC5ExzN3215Q',
    appId: '1:969788980087:ios:5c67bc28d574093b7dff72',
    messagingSenderId: '969788980087',
    projectId: 'medicine-b7e88',
    storageBucket: 'medicine-b7e88.appspot.com',
    iosBundleId: 'com.example.medicine.RunnerTests',
  );
}
